
/*
 * CommandCodes.h
 *
 *  Created on: 21/06/2022
 *      Author: jmotp
 */

#ifndef TRANSDUCERSERVICES_COMMANDCODES_H_
#define TRANSDUCERSERVICES_COMMANDCODES_H_

#define COMMON_CMD 1
#define XDCR_IDLE 2
#define XDCR_OPERATE 3
#define XDCR_EITHER 4
#define TIM_SLEEP_CMD 5
#define TIM_ACTIVE_CMD 6
#define ANY_STATE 7
#define REGISTER_CMD 0x80

//COMMON_CMD
#define QUERY_TEDS 1
#define READ_TEDS_SEGMENT 2
#define WRITE_TEDS_SEGMENT 3
#define UPDATE_TEDS 4
#define RUN_SELF_TEST 5

//XDCR_OPERATE
#define READ_TRANSDUCERCHANNEL_DATA 1
#define WRITE_TRANSDUCERCHANNEL_DATA 2
#define TRIGGER_TRANSDUCERCHANNEL 3
#define ABORT_TRANSDUCERCHANNEL 4


//REGISTER
#define DISCOVERY 2
#endif /* TRANSDUCERSERVICES_COMMANDCODES_H_ */
