
/*
 * CommandCodes.h
 *
 *  Created on: 21/06/2022
 *      Author: jmotp
 */

#ifndef TRANSDUCERSERVICES_COMMANDCODES_H_
#define TRANSDUCERSERVICES_COMMANDCODES_H_

#define COMMON_CMD 1
#define XDCR_OPERATE 3
#define REGISTER_CMD 0x80

//COMMON_CMD
#define READ_TEDS_SEGMENT 2
#define WRITE_TEDS_SEGMENT 3


//XDCR_OPERATE
#define READ_TRANSDUCERCHANNEL_DATA 1

//REGISTER
#define DISCOVERY 2
#endif /* TRANSDUCERSERVICES_COMMANDCODES_H_ */
